### ISSUE TITLE
Emoji font fallbacks

### ISSUE THREAD

**Issue by webknjaz** [mbifulco/blog#342]
Hi, I hit your post https://mike.biful.co/i-have-to-tell-you-about-dependabot and the :robot: emoji is represented poorly by the fallback font available on my system even though I have good fonts with emojis in place.

![poor-robot-emoji-in-blog](https://user-images.githubusercontent.com/578543/69877797-73dce300-12c3-11ea-934e-d334fc78b820.png)

So I just wanted to give you heads up about this in case it's something you'd like to fix.

As a hint, I usually [add the following fonts](https://github.com/sanitizers/octomachinery/commit/787226b9deb33e622713ed88ef70de69be648768) at the end of `font-family`: `"apple color emoji", "segoe ui emoji", "android emoji", "emojisymbols", "emojione mozilla", "twemoji mozilla", "segoe ui symbol", "noto color emoji"`.

After adding these to `font-family` of the `body {}` section via DevTools I see:
![fix-robot-in-blog](https://user-images.githubusercontent.com/578543/69877953-d0d89900-12c3-11ea-9e7a-011efc7d589d.png)

```diff
 body {
     margin: 0;
     padding: 0;
-    font-family: Inter UI,-apple-system,BlinkMacSystemFont,Roboto,Segoe UI,Helvetica,Arial,sans-serif;
+    font-family: Inter UI,-apple-system,BlinkMacSystemFont,Roboto,Segoe UI,Helvetica,Arial,sans-serif,"apple color emoji", "segoe ui emoji", "android emoji", "emojisymbols", "emojione mozilla", "twemoji mozilla", "segoe ui symbol", "noto color emoji";
     font-size: 1rem;
     font-weight: 600;
     line-height: 1.54;
     background-color: #fff;
     color: #222;
     text-rendering: optimizeLegibility;
     -webkit-font-smoothing: antialiased;
     font-feature-settings: "liga","tnum","case","calt","zero","ss01","locl";
     -webkit-overflow-scrolling: touch;
     -webkit-text-size-adjust: 100%;
}
```

Have a nice day :)

**Comment by mbifulco** [comment]
Hey there, that's an amazing tip, thank you! I'll get that into an upcoming site release.  I appreciate it, @webknjaz!

**Comment by mbifulco** [comment]
Hey @webknjaz - any chance you can check out the [deploy preview](https://deploy-preview-343--mike-biful-co.netlify.com/) in #343 to see if the issue is resolved on your device?

**Comment by mbifulco** [comment]
And while I'm at it - which device/browser/OS were you using?

**Comment by webknjaz** [comment]
Yep. It's resolved. I'm using Gentoo Linux so it's a pretty hand-crafted env. But I'm pretty sure that there's a lot of other distros that have various font defaults :)
