### ISSUE TITLE
You got too many likes! (mobile wrapping)

### ISSUE THREAD

**Issue by qw-in** [mbifulco/blog#597]
Cool post - wish I could fix everything with the click of a button!

![Screenshot_2022-05-22-21-12-28-56_3aea4af51f236e4932235fdada7d1643.jpg](https://user-images.githubusercontent.com/19194187/169741950-e300ee48-3cfd-4c8a-8646-3b62854fd1bd.jpg)

Android FF

**Comment by mbifulco** [comment]
It's a good problem to have, but one worth fixing! Thanks for calling this out.
